name: Release
on:
  push:
    tags:
      - "[0-9]*.[0-9]*"
  
permissions: {} 

jobs:
    build:
      runs-on: ubuntu-24.04-arm
      permissions:
        contents: write
        id-token: write
        attestations: write

      steps:
        - name: Checkout code
          uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
          with:
            persist-credentials: false

        - name: Install deps
          run: |
            sudo apt-get update
            sudo apt-get install build-essential devscripts debhelper lintian

        - name: Build
          run: |
            bash run.sh
          
        - name: GitHub Attestations for binaries
          uses: actions/attest@ce27ba3b4a9a139d9a20a4a07d69fabb52f1e5bc # v2.4.0
          with:
            predicate-type: 'https://in-toto.io/attestation/release'
            predicate: '{}'
            subject-path: |
              *.deb

        - name: Release
          uses: softprops/action-gh-release@d5382d3e6f2fa7bd53cb749d33091853d4985daf # v2.3.0
          if: github.ref_type == 'tag'
          with:
            files: "*.deb"